import enum
from collections.abc import Iterator
from typing import overload

class ResolveMethod(enum.Enum):
    ERROR = 0

    WEAK = 1

    ZEROS = 2

    ONES = 3

    RANDOM = 4

class Logic:
    @overload
    def __init__(self, arg: Logic) -> None: ...
    @overload
    def __init__(self, arg: Bit, /) -> None: ...
    @overload
    def __init__(self, arg: str, /) -> None: ...
    @overload
    def __init__(self, arg: int, /) -> None: ...
    def __str__(self) -> str: ...
    def __index__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    @overload
    def __eq__(self, arg: Logic, /) -> bool: ...
    @overload
    def __eq__(self, arg: Bit, /) -> bool: ...
    @overload
    def __eq__(self, arg: int, /) -> bool: ...
    @overload
    def __eq__(self, arg: str, /) -> bool: ...
    @overload
    def __or__(self, arg: Logic, /) -> Logic: ...
    @overload
    def __or__(self, arg: Bit, /) -> Logic: ...
    @overload
    def __and__(self, arg: Logic, /) -> Logic: ...
    @overload
    def __and__(self, arg: Bit, /) -> Logic: ...
    @overload
    def __xor__(self, arg: Logic, /) -> Logic: ...
    @overload
    def __xor__(self, arg: Bit, /) -> Logic: ...
    def __invert__(self) -> Logic: ...
    @property
    def is_resolvable(self) -> bool: ...
    @overload
    def resolve(self, arg: str, /) -> Logic: ...
    @overload
    def resolve(self, arg: ResolveMethod, /) -> Logic: ...
    def __copy__(self) -> Logic: ...
    def __deepcopy__(self, arg: dict, /) -> Logic: ...

class Bit:
    @overload
    def __init__(self, arg: Bit) -> None: ...
    @overload
    def __init__(self, arg: Logic, /) -> None: ...
    @overload
    def __init__(self, arg: str, /) -> None: ...
    @overload
    def __init__(self, arg: int, /) -> None: ...
    def __str__(self) -> str: ...
    def __index__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    @overload
    def __eq__(self, arg: Bit, /) -> bool: ...
    @overload
    def __eq__(self, arg: Logic, /) -> bool: ...
    @overload
    def __eq__(self, arg: int, /) -> bool: ...
    @overload
    def __eq__(self, arg: str, /) -> bool: ...
    @overload
    def __or__(self, arg: Bit, /) -> Bit: ...
    @overload
    def __or__(self, arg: Logic, /) -> Logic: ...
    @overload
    def __and__(self, arg: Bit, /) -> Bit: ...
    @overload
    def __and__(self, arg: Logic, /) -> Logic: ...
    @overload
    def __xor__(self, arg: Bit, /) -> Bit: ...
    @overload
    def __xor__(self, arg: Logic, /) -> Logic: ...
    def __invert__(self) -> Bit: ...
    @property
    def is_resolvable(self) -> bool: ...
    @overload
    def resolve(self, arg: str, /) -> Bit: ...
    @overload
    def resolve(self, arg: ResolveMethod, /) -> Bit: ...
    def __copy__(self) -> Bit: ...
    def __deepcopy__(self, arg: dict, /) -> Bit: ...

class Direction(enum.Enum):
    TO = 0

    DOWNTO = 1

class Range:
    @overload
    def __init__(self, left: int, direction: Direction, right: int) -> None: ...
    @overload
    def __init__(self, left: int, direction: str, right: int) -> None: ...
    @overload
    def __init__(self, left: int, right: int) -> None: ...
    def to_range(self) -> object: ...
    @staticmethod
    def from_range(range: object) -> Range: ...
    @property
    def left(self) -> int: ...
    @property
    def right(self) -> int: ...
    @property
    def direction(self) -> str: ...
    def __len__(self) -> int: ...
    def __contains__(self, arg: int) -> bool: ...
    def __iter__(self) -> Iterator: ...
    def __reversed__(self) -> Iterator: ...
    @overload
    def __getitem__(self, arg: int) -> int: ...
    @overload
    def __getitem__(self, arg: slice) -> Range: ...
    def __eq__(self, arg: Range) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    @overload
    def index(self, arg: int) -> int: ...
    @overload
    def index(self, arg0: int, arg1: int) -> int: ...
    @overload
    def index(self, arg0: int, arg1: int, arg2: int) -> int: ...
    def count(self, arg: int) -> int: ...
    def __copy__(self) -> Range: ...
    def __deepcopy__(self, arg: object, /) -> Range: ...
