import enum
from collections.abc import Iterator
from typing import overload

class ResolveMethod(enum.Enum):
    ERROR = 0

    WEAK = 1

    ZEROS = 2

    ONES = 3

    RANDOM = 4

class Logic:
    @overload
    def __init__(self, arg: Logic, /) -> None: ...
    @overload
    def __init__(self, arg: Bit, /) -> None: ...
    @overload
    def __init__(self, arg: str, /) -> None: ...
    @overload
    def __init__(self, arg: int, /) -> None: ...
    def __str__(self) -> str: ...
    def __index__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    @overload
    def __eq__(self, arg: Logic, /) -> bool: ...
    @overload
    def __eq__(self, arg: Bit, /) -> bool: ...
    @overload
    def __eq__(self, arg: int, /) -> bool: ...
    @overload
    def __eq__(self, arg: str, /) -> bool: ...
    @overload
    def __or__(self, arg: Logic, /) -> Logic: ...
    @overload
    def __or__(self, arg: Bit, /) -> Logic: ...
    @overload
    def __and__(self, arg: Logic, /) -> Logic: ...
    @overload
    def __and__(self, arg: Bit, /) -> Logic: ...
    @overload
    def __xor__(self, arg: Logic, /) -> Logic: ...
    @overload
    def __xor__(self, arg: Bit, /) -> Logic: ...
    def __invert__(self) -> Logic: ...
    @property
    def is_resolvable(self) -> bool: ...
    def resolve(self, arg: str, /) -> Logic: ...
    def __copy__(self) -> Logic: ...
    def __deepcopy__(self, arg: dict, /) -> Logic: ...

class Bit:
    @overload
    def __init__(self, arg: Bit, /) -> None: ...
    @overload
    def __init__(self, arg: Logic, /) -> None: ...
    @overload
    def __init__(self, arg: str, /) -> None: ...
    @overload
    def __init__(self, arg: int, /) -> None: ...
    def __str__(self) -> str: ...
    def __index__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    @overload
    def __eq__(self, arg: Bit, /) -> bool: ...
    @overload
    def __eq__(self, arg: Logic, /) -> bool: ...
    @overload
    def __eq__(self, arg: int, /) -> bool: ...
    @overload
    def __eq__(self, arg: str, /) -> bool: ...
    @overload
    def __or__(self, arg: Bit, /) -> Bit: ...
    @overload
    def __or__(self, arg: Logic, /) -> Logic: ...
    @overload
    def __and__(self, arg: Bit, /) -> Bit: ...
    @overload
    def __and__(self, arg: Logic, /) -> Logic: ...
    @overload
    def __xor__(self, arg: Bit, /) -> Bit: ...
    @overload
    def __xor__(self, arg: Logic, /) -> Logic: ...
    def __invert__(self) -> Bit: ...
    @property
    def is_resolvable(self) -> bool: ...
    def resolve(self, arg: str, /) -> Bit: ...
    def __copy__(self) -> Bit: ...
    def __deepcopy__(self, arg: dict, /) -> Bit: ...

class Direction(enum.Enum):
    TO = 0

    DOWNTO = 1

class Range:
    @overload
    def __init__(self, left: int, direction: Direction, right: int) -> None: ...
    @overload
    def __init__(self, left: int, direction: str, right: int) -> None: ...
    @overload
    def __init__(self, left: int, right: int) -> None: ...
    def to_range(self) -> object: ...
    @staticmethod
    def from_range(range: object) -> Range: ...
    @property
    def left(self) -> int: ...
    @property
    def right(self) -> int: ...
    @property
    def direction(self) -> str: ...
    def __len__(self) -> int: ...
    def __contains__(self, arg: int, /) -> bool: ...
    def __iter__(self) -> Iterator: ...
    def __reversed__(self) -> Iterator: ...
    @overload
    def __getitem__(self, arg: int, /) -> int: ...
    @overload
    def __getitem__(self, arg: slice, /) -> Range: ...
    def __eq__(self, arg: object, /) -> object: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    @overload
    def index(self, arg: int, /) -> int: ...
    @overload
    def index(self, arg0: int, arg1: int, /) -> int: ...
    @overload
    def index(self, arg0: int, arg1: int, arg2: int, /) -> int: ...
    def count(self, arg: int, /) -> int: ...
    def __copy__(self) -> Range: ...
    def __deepcopy__(self, arg: object, /) -> Range: ...

class LogicArray:
    def __init__(self, value: object, range: object | None = None) -> None: ...
    @overload
    @staticmethod
    def from_unsigned(
        value: int, range: object, *, on_overflow: str = "error"
    ) -> LogicArray: ...
    @overload
    @staticmethod
    def from_unsigned(
        value: Unsigned, range: object, *, on_overflow: str = "error"
    ) -> LogicArray: ...
    @overload
    @staticmethod
    def from_signed(
        value: int, range: object, *, on_overflow: str = "error"
    ) -> LogicArray: ...
    @overload
    @staticmethod
    def from_signed(
        value: Signed, range: object, *, on_overflow: str = "error"
    ) -> LogicArray: ...
    @staticmethod
    def from_bytes(
        value: object, range: object | None = None, *, byteorder: str
    ) -> LogicArray: ...
    def to_unsigned(self) -> Unsigned: ...
    def to_signed(self) -> Signed: ...
    def to_bytes(self, *, byteorder: str) -> bytes: ...
    @property
    def integer(self) -> Unsigned: ...
    @integer.setter
    def integer(self, arg: int, /) -> None: ...
    @property
    def signed_integer(self) -> Signed: ...
    @signed_integer.setter
    def signed_integer(self, arg: int, /) -> None: ...
    @property
    def binstr(self) -> str: ...
    @binstr.setter
    def binstr(self, arg: str, /) -> None: ...
    @property
    def buff(self) -> bytes: ...
    @buff.setter
    def buff(self, arg: object, /) -> None: ...
    @property
    def range(self) -> Range: ...
    @range.setter
    def range(self, arg: object, /) -> None: ...
    @property
    def left(self) -> int: ...
    @property
    def right(self) -> int: ...
    @property
    def direction(self) -> str: ...
    @property
    def is_resolvable(self) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Logic]: ...
    def __reversed__(self) -> Iterator[Logic]: ...
    def __contains__(self, arg: Logic, /) -> bool: ...
    @overload
    def __getitem__(self, arg: int, /) -> Logic: ...
    @overload
    def __getitem__(self, arg: slice, /) -> LogicArray: ...
    @overload
    def __setitem__(self, arg0: int, arg1: object, /) -> None: ...
    @overload
    def __setitem__(self, arg0: slice, arg1: object, /) -> None: ...
    def index(
        self, value: object, start: int | None = None, stop: int | None = None
    ) -> int: ...
    def count(self, arg: Logic, /) -> int: ...
    def __and__(self, arg: LogicArray, /) -> LogicArray: ...
    def __or__(self, arg: LogicArray, /) -> LogicArray: ...
    def __xor__(self, arg: LogicArray, /) -> LogicArray: ...
    def __invert__(self) -> LogicArray: ...
    @overload
    def __eq__(self, arg: LogicArray, /) -> bool: ...
    @overload
    def __eq__(self, arg: str, /) -> bool: ...
    @overload
    def __eq__(self, arg: int, /) -> bool: ...
    @overload
    def __eq__(self, arg: object, /) -> object: ...
    def resolve(self, resolver: str) -> LogicArray: ...
    def __str__(self) -> str: ...
    def __int__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __index__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __copy__(self) -> LogicArray: ...
    def __deepcopy__(self, arg: dict, /) -> LogicArray: ...

class BitArray:
    def __init__(self, value: object, range: object | None = None) -> None: ...
    @property
    def range(self) -> Range: ...
    @property
    def left(self) -> int: ...
    @property
    def right(self) -> int: ...
    @property
    def direction(self) -> str: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Bit]: ...
    def __reversed__(self) -> Iterator[Bit]: ...
    def __contains__(self, arg: Bit, /) -> bool: ...
    @overload
    def __getitem__(self, arg: int, /) -> Bit: ...
    @overload
    def __getitem__(self, arg: slice, /) -> BitArray: ...
    @overload
    def __setitem__(self, arg0: int, arg1: object, /) -> None: ...
    @overload
    def __setitem__(self, arg0: slice, arg1: object, /) -> None: ...
    def index(
        self, value: object, start: int | None = None, stop: int | None = None
    ) -> int: ...
    def count(self, arg: Bit, /) -> int: ...
    def __and__(self, arg: BitArray, /) -> BitArray: ...
    def __or__(self, arg: BitArray, /) -> BitArray: ...
    def __xor__(self, arg: BitArray, /) -> BitArray: ...
    def __invert__(self) -> BitArray: ...
    @overload
    def __eq__(self, arg: BitArray, /) -> bool: ...
    @overload
    def __eq__(self, arg: str, /) -> bool: ...
    @overload
    def __eq__(self, arg: object, /) -> bool: ...
    def resolve(self, resolver: str) -> BitArray: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __copy__(self) -> BitArray: ...
    def __deepcopy__(self, arg: dict, /) -> BitArray: ...

class Unsigned:
    @overload
    def __init__(self, arg0: int, arg1: int, /) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, /) -> None: ...
    def __or__(self, arg: Unsigned, /) -> Unsigned: ...
    def __and__(self, arg: Unsigned, /) -> Unsigned: ...
    def __xor__(self, arg: Unsigned, /) -> Unsigned: ...
    def __invert__(self) -> Unsigned: ...
    def __getitem__(self, arg: int, /) -> bool: ...
    def __neg__(self) -> Signed: ...
    def __pos__(self) -> Signed: ...
    @overload
    def __eq__(self, arg: Unsigned, /) -> bool: ...
    @overload
    def __eq__(self, arg: int, /) -> bool: ...
    def __lt__(self, arg: Unsigned, /) -> bool: ...
    def __gt__(self, arg: Unsigned, /) -> bool: ...
    def __le__(self, arg: Unsigned, /) -> bool: ...
    def __ge__(self, arg: Unsigned, /) -> bool: ...
    @overload
    def __lshift__(self, arg: int, /) -> Unsigned: ...
    @overload
    def __lshift__(self, arg: Unsigned, /) -> Unsigned: ...
    @overload
    def __lshift__(self, arg: Signed, /) -> Unsigned: ...
    @overload
    def __ilshift__(self, arg: int, /) -> Unsigned: ...
    @overload
    def __ilshift__(self, arg: Unsigned, /) -> Unsigned: ...
    @overload
    def __ilshift__(self, arg: Signed, /) -> Unsigned: ...
    @overload
    def __rshift__(self, arg: int, /) -> Unsigned: ...
    @overload
    def __rshift__(self, arg: Unsigned, /) -> Unsigned: ...
    @overload
    def __rshift__(self, arg: Signed, /) -> Unsigned: ...
    @overload
    def __irshift__(self, arg: int, /) -> Unsigned: ...
    @overload
    def __irshift__(self, arg: Unsigned, /) -> Unsigned: ...
    @overload
    def __irshift__(self, arg: Signed, /) -> Unsigned: ...
    def __int__(self) -> int: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __add__(self, arg: Unsigned, /) -> Unsigned: ...
    @overload
    def __iadd__(self, arg: Unsigned, /) -> Unsigned: ...
    @overload
    def __iadd__(self, arg: int, /) -> Unsigned: ...
    @overload
    def __iadd__(self, arg: Signed, /) -> Unsigned: ...
    def __mul__(self, arg: Unsigned, /) -> Unsigned: ...
    @overload
    def __imul__(self, arg: Unsigned, /) -> Unsigned: ...
    @overload
    def __imul__(self, arg: int, /) -> Unsigned: ...
    @overload
    def __imul__(self, arg: Signed, /) -> Unsigned: ...
    def __truediv__(self, arg: Unsigned, /) -> Unsigned: ...
    @overload
    def __itruediv__(self, arg: Unsigned, /) -> Unsigned: ...
    @overload
    def __itruediv__(self, arg: int, /) -> Unsigned: ...
    @overload
    def __itruediv__(self, arg: Signed, /) -> Unsigned: ...
    def __floordiv__(self, arg: Unsigned, /) -> Unsigned: ...
    @overload
    def __ifloordiv__(self, arg: Unsigned, /) -> Unsigned: ...
    @overload
    def __ifloordiv__(self, arg: int, /) -> Unsigned: ...
    @overload
    def __ifloordiv__(self, arg: Signed, /) -> Unsigned: ...
    def __mod__(self, arg: Unsigned, /) -> Unsigned: ...
    @overload
    def __imod__(self, arg: Unsigned, /) -> Unsigned: ...
    @overload
    def __imod__(self, arg: int, /) -> Unsigned: ...
    @overload
    def __imod__(self, arg: Signed, /) -> Unsigned: ...
    def __sub__(self, arg: Unsigned, /) -> Signed: ...
    @overload
    def __isub__(self, arg: Unsigned, /) -> Unsigned: ...
    @overload
    def __isub__(self, arg: int, /) -> Unsigned: ...
    @overload
    def __isub__(self, arg: Signed, /) -> Unsigned: ...

class Signed:
    @overload
    def __init__(self, arg0: int, arg1: int, /) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int, /) -> None: ...
    def __or__(self, arg: Signed, /) -> Signed: ...
    def __and__(self, arg: Signed, /) -> Signed: ...
    def __xor__(self, arg: Signed, /) -> Signed: ...
    def __invert__(self) -> Signed: ...
    def __getitem__(self, arg: int, /) -> bool: ...
    def __neg__(self) -> Signed: ...
    def __pos__(self) -> Signed: ...
    @overload
    def __eq__(self, arg: Signed, /) -> bool: ...
    @overload
    def __eq__(self, arg: int, /) -> bool: ...
    def __lt__(self, arg: Signed, /) -> bool: ...
    def __gt__(self, arg: Signed, /) -> bool: ...
    def __le__(self, arg: Signed, /) -> bool: ...
    def __ge__(self, arg: Signed, /) -> bool: ...
    @overload
    def __lshift__(self, arg: int, /) -> Signed: ...
    @overload
    def __lshift__(self, arg: Unsigned, /) -> Signed: ...
    @overload
    def __lshift__(self, arg: Signed, /) -> Signed: ...
    @overload
    def __ilshift__(self, arg: int, /) -> Signed: ...
    @overload
    def __ilshift__(self, arg: Unsigned, /) -> Signed: ...
    @overload
    def __ilshift__(self, arg: Signed, /) -> Signed: ...
    @overload
    def __rshift__(self, arg: int, /) -> Signed: ...
    @overload
    def __rshift__(self, arg: Unsigned, /) -> Signed: ...
    @overload
    def __rshift__(self, arg: Signed, /) -> Signed: ...
    @overload
    def __irshift__(self, arg: int, /) -> Signed: ...
    @overload
    def __irshift__(self, arg: Unsigned, /) -> Signed: ...
    @overload
    def __irshift__(self, arg: Signed, /) -> Signed: ...
    def __int__(self) -> int: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __add__(self, arg: Signed, /) -> Signed: ...
    @overload
    def __iadd__(self, arg: Unsigned, /) -> Signed: ...
    @overload
    def __iadd__(self, arg: int, /) -> Signed: ...
    @overload
    def __iadd__(self, arg: Signed, /) -> Signed: ...
    def __mul__(self, arg: Signed, /) -> Signed: ...
    @overload
    def __imul__(self, arg: Unsigned, /) -> Signed: ...
    @overload
    def __imul__(self, arg: int, /) -> Signed: ...
    @overload
    def __imul__(self, arg: Signed, /) -> Signed: ...
    def __truediv__(self, arg: Signed, /) -> Signed: ...
    @overload
    def __itruediv__(self, arg: Unsigned, /) -> Signed: ...
    @overload
    def __itruediv__(self, arg: int, /) -> Signed: ...
    @overload
    def __itruediv__(self, arg: Signed, /) -> Signed: ...
    def __floordiv__(self, arg: Signed, /) -> Signed: ...
    @overload
    def __ifloordiv__(self, arg: Unsigned, /) -> Signed: ...
    @overload
    def __ifloordiv__(self, arg: int, /) -> Signed: ...
    @overload
    def __ifloordiv__(self, arg: Signed, /) -> Signed: ...
    def __mod__(self, arg: Signed, /) -> Signed: ...
    @overload
    def __imod__(self, arg: Signed, /) -> Signed: ...
    @overload
    def __imod__(self, arg: Unsigned, /) -> Signed: ...
    @overload
    def __imod__(self, arg: int, /) -> Signed: ...
    def __sub__(self, arg: Signed, /) -> Signed: ...
    @overload
    def __isub__(self, arg: Unsigned, /) -> Signed: ...
    @overload
    def __isub__(self, arg: int, /) -> Signed: ...
    @overload
    def __isub__(self, arg: Signed, /) -> Signed: ...

class Sfixed:
    @overload
    def __init__(self, value: int, range: Range) -> None: ...
    @overload
    def __init__(self, value: float, range: Range) -> None: ...
    @overload
    def __init__(self, range: Range, value: int) -> None: ...
    @overload
    def __init__(self, range: Range, value: float) -> None: ...
    def __pos__(self) -> Sfixed: ...
    def __neg__(self) -> Sfixed: ...
    def __abs__(self) -> Sfixed: ...
    def __sub__(self, arg: Sfixed, /) -> Sfixed: ...
    def __isub__(self, arg: Sfixed, /) -> Sfixed: ...
    @property
    def range(self) -> Range: ...
    @property
    def left(self) -> int: ...
    @property
    def right(self) -> int: ...
    @property
    def direction(self) -> str: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __getitem__(self, arg: int, /) -> bool: ...
    def __setitem__(self, arg0: int, arg1: bool, /) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, arg: Sfixed, /) -> bool: ...
    def __lt__(self, arg: Sfixed, /) -> bool: ...
    def __le__(self, arg: Sfixed, /) -> bool: ...
    def __gt__(self, arg: Sfixed, /) -> bool: ...
    def __ge__(self, arg: Sfixed, /) -> bool: ...
    def __lshift__(self, arg: int, /) -> Sfixed: ...
    def __rshift__(self, arg: int, /) -> Sfixed: ...
    def __ilshift__(self, arg: int, /) -> Sfixed: ...
    def __irshift__(self, arg: int, /) -> Sfixed: ...
    def __add__(self, arg: Sfixed, /) -> Sfixed: ...
    def __iadd__(self, arg: Sfixed, /) -> Sfixed: ...
    def __mul__(self, arg: Sfixed, /) -> Sfixed: ...
    def __imul__(self, arg: Sfixed, /) -> Sfixed: ...
    def __truediv__(self, arg: Sfixed, /) -> Sfixed: ...
    def __itruediv__(self, arg: Sfixed, /) -> Sfixed: ...
    def __mod__(self, arg: Sfixed, /) -> Sfixed: ...
    def __imod__(self, arg: Sfixed, /) -> Sfixed: ...

class Ufixed:
    @overload
    def __init__(self, value: int, range: Range) -> None: ...
    @overload
    def __init__(self, value: float, range: Range) -> None: ...
    @overload
    def __init__(self, range: Range, value: int) -> None: ...
    @overload
    def __init__(self, range: Range, value: float) -> None: ...
    def __pos__(self) -> Sfixed: ...
    def __neg__(self) -> Sfixed: ...
    def __sub__(self, arg: Ufixed, /) -> Sfixed: ...
    def __isub__(self, arg: Ufixed, /) -> Ufixed: ...
    @property
    def range(self) -> Range: ...
    @property
    def left(self) -> int: ...
    @property
    def right(self) -> int: ...
    @property
    def direction(self) -> str: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __getitem__(self, arg: int, /) -> bool: ...
    def __setitem__(self, arg0: int, arg1: bool, /) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, arg: Ufixed, /) -> bool: ...
    def __lt__(self, arg: Ufixed, /) -> bool: ...
    def __le__(self, arg: Ufixed, /) -> bool: ...
    def __gt__(self, arg: Ufixed, /) -> bool: ...
    def __ge__(self, arg: Ufixed, /) -> bool: ...
    def __lshift__(self, arg: int, /) -> Ufixed: ...
    def __rshift__(self, arg: int, /) -> Ufixed: ...
    def __ilshift__(self, arg: int, /) -> Ufixed: ...
    def __irshift__(self, arg: int, /) -> Ufixed: ...
    def __add__(self, arg: Ufixed, /) -> Ufixed: ...
    def __iadd__(self, arg: Ufixed, /) -> Ufixed: ...
    def __mul__(self, arg: Ufixed, /) -> Ufixed: ...
    def __imul__(self, arg: Ufixed, /) -> Ufixed: ...
    def __truediv__(self, arg: Ufixed, /) -> Ufixed: ...
    def __itruediv__(self, arg: Ufixed, /) -> Ufixed: ...
    def __mod__(self, arg: Ufixed, /) -> Ufixed: ...
    def __imod__(self, arg: Ufixed, /) -> Ufixed: ...
