name: Cocotb Integration Tests

on:
  workflow_dispatch:

  push:
    branches:
      - dev
    tags:
      - '*'
  pull_request:
    branches:
    - dev

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: "true"

      - name: Install dependencies
        run: |
          uv sync

      - name: Checkout cocotb
        uses: actions/checkout@v6
        with:
          repository: cocotb/cocotb
          path: cocotb

      - name: Run patched cocotb tests
        run: |
          make clean_coverage
          make integration_tests
          make generate_report

      - name: Upload coverage reports to Codecov
        if: github.repository == 'ktbarrett/coconext'
        uses: codecov/codecov-action@v6
        with:
          disable_search: true
          plugins: noop
          files: .python-coverage.xml,.cpp-coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'dev') }}
