name: Regression Tests

on:
  workflow_call:
    inputs:
      make_targets:
        required: true
        type: string
      collect_coverage:
        required: false
        type: boolean
        default: false
      download_sdist_artifacts:
        required: false
        type: boolean
        default: false
      download_wheel_artifacts:
        required: false
        type: boolean
        default: false

jobs:
    generate_envs:
      runs-on: ubuntu-latest
      name: Generate a list of environments to run tests against
      steps:
      - uses: actions/checkout@v7
      - run: ./.github/generate-envs.py --output-format=gha --gha-output-file="$GITHUB_OUTPUT"
        id: run_generate_script
      outputs:
        envs: ${{ steps.run_generate_script.outputs.envs }}

    tests:
      needs: generate_envs

      name: ${{matrix.name}}
      runs-on: ${{matrix.os}}
      timeout-minutes: 60

      env:
        SIM: ${{ matrix.simulator }}
        TOPLEVEL_LANG: ${{ matrix.toplevel_lang }}
        CXX_STANDARD: ${{ matrix.cxx-standard }}

      strategy:
        fail-fast: false
        matrix:
          include: ${{ fromJson(needs.generate_envs.outputs.envs) }}

      steps:
      - uses: actions/checkout@v7
        with:
          # GitHub PR's create a merge commit, and Actions are run on that commit.
          # Codecov's uploader needs the previous commit (tip of PR branch) to associate coverage correctly.
          # A fetch depth of 2 provides enough information without fetching the entire history.
          fetch-depth: 2

      - name: Download Wheel Artifacts
        if: inputs.download_wheel_artifacts
        uses: actions/download-artifact@v8
        with:
          name: wheels-${{ matrix.os }}
          path: dist

      - name: Download Sdist Artifacts
        if: inputs.download_sdist_artifacts
        uses: actions/download-artifact@v8
        with:
          name: sdist
          path: dist

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{matrix.python-version}}
          allow-prereleases: true

      - name: Setup NVC
        uses: nickg/setup-nvc@v1
        if: matrix.simulator == 'nvc'
        with:
          version: ${{matrix.simulator-version}}

      - name: Setup Icarus (MacOS)
        if: matrix.simulator == 'icarus' && startsWith(matrix.os, 'macos')
        run: |
          brew install icarus-verilog

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: "true"

      - name: Install Testing Dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt install -y make libgtest-dev llvm

      - name: Checkout cocotb
        if: contains(inputs.make_targets, 'integration_tests')
        uses: actions/checkout@v7
        with:
          repository: cocotb/cocotb
          path: cocotb

      - name: Run tests
        env:
          CC: ${{ matrix.cc || 'gcc' }}
          CXX: ${{ matrix.cxx || 'g++' }}
          GCOV_EXECUTABLE: ${{ matrix.gcov || 'gcov' }}
          CXX_STANDARD: ${{ matrix.cxx-standard }}
          DEV_BUILD_DEP_GROUP: dev_tests
        run: |
          make ${{ inputs.make_targets }}

      - name: Check stubs haven't diverged
        run: |
          git diff --exit-code -- python/_coconext.pyi

      - name: Upload coverage reports to Codecov
        if: github.repository == 'ktbarrett/coconext' && inputs.collect_coverage
        uses: codecov/codecov-action@v7.0.0
        with:
          disable_search: true
          plugins: noop
          files: .python-coverage.xml,.cpp-coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          fail_ci_if_error: true
