name: Tests

on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev

jobs:
  tests:
    name: Tests (Python ${{matrix.python-version}} | ${{matrix.simulator}})
    runs-on: ${{matrix.os}}

    env:
      SIM: ${{matrix.simulator}}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        simulator: [nvc]
        os: [ubuntu-24.04]
        nvc_version: ["1.16.1"]

    steps:
    - uses: actions/checkout@v4
      with:
        # GitHub PR's create a merge commit, and Actions are run on that commit.
        # Codecov's uploader needs the previous commit (tip of PR branch) to associate coverage correctly.
        # A fetch depth of 2 provides enough information without fetching the entire history.
        fetch-depth: 2

    - uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}
        allow-prereleases: true

    - name: Download NVC
      uses: robinraju/release-downloader@v1
      with:
        repository: nickg/nvc
        tag: r${{ matrix.nvc_version }}
        filename: nvc_${{ matrix.nvc_version }}-1_amd64_${{ matrix.os }}.deb

    - name: Install NVC
      run: |
        sudo dpkg -i nvc_${{ matrix.nvc_version }}-1_amd64_${{ matrix.os }}.deb

    - name: Install Testing Dependencies
      # Must install cocotb from github until 2.0 is released
      run: |
        pip install nox coverage

    - name: Run tests
      run: |
        nox -s tests

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'dev') }}
