name: Tests

on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev

jobs:
  tests:
    name: Tests (Python ${{matrix.python-version}} | ${{matrix.simulator}}${{ matrix.cc != '' && format(' | {0}', matrix.cc) || '' }}${{ !startsWith(matrix.os, 'ubuntu') && format(' | {0}', matrix.os) || '' }})
    runs-on: ${{matrix.os}}

    env:
      SIM: ${{matrix.simulator}}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        simulator: [nvc]
        os: [ubuntu-24.04]
        nvc-version: ["1.20.1"]
        include:
          # Ubuntu with Clang
          - python-version: "3.13"
            nvc-version: "1.20.1"
            os: "ubuntu-24.04"
            simulator: "nvc"
            cc: "clang"
            cxx: "clang++"
            gcov: "llvm-cov gcov"
          # MacOS ARM and Intel
          - python-version: "3.13"
            simulator: "nvc"
            os: "macos-26"
          - python-version: "3.13"
            simulator: "nvc"
            os: "macos-15-intel"

    steps:
    - uses: actions/checkout@v6
      with:
        # GitHub PR's create a merge commit, and Actions are run on that commit.
        # Codecov's uploader needs the previous commit (tip of PR branch) to associate coverage correctly.
        # A fetch depth of 2 provides enough information without fetching the entire history.
        fetch-depth: 2

    - uses: actions/setup-python@v6
      with:
        python-version: ${{matrix.python-version}}
        allow-prereleases: true

    - name: Setup ccache (pt. 1)
      uses: hendrikmuhs/ccache-action@v1.2.23
      with:
        create-symlink: true
    - name: Setup ccache (pt. 2)
      run: |
        echo "/usr/lib/ccache" >> $GITHUB_PATH
        echo "/usr/local/opt/ccache/libexec" >> $GITHUB_PATH

    - name: Set up NVC
      uses: nickg/setup-nvc@v1
      with:
        version: ${{matrix.nvc-version}}

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        activate-environment: "true"

    - name: Install Testing Dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt install -y make libgtest-dev llvm

    - name: Run tests
      env:
        CC: ${{ matrix.cc || 'gcc' }}
        CXX: ${{matrix.cxx || 'g++'}}
        GCOV_EXECUTABLE: ${{matrix.gcov || 'gcov'}}
      run: |
        make tests

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v6
      with:
        disable_search: true
        plugins: noop
        files: .python-coverage.xml,.cpp-coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
        fail_ci_if_error: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'dev') }}
