name: Tests

on:
  push:
    branches:
    - dev
    paths-ignore:
    - 'docs/dev/**'
  pull_request:
    branches:
    - dev
    paths-ignore:
    - 'docs/dev/**'

jobs:
  tests:
    name: Tests (Python ${{matrix.python-version}} | ${{matrix.simulator}}${{matrix.cxx-standard != '20' && format(' | C++{0}', matrix.cxx-standard) || '' }}${{ matrix.cc != '' && format(' | {0}', matrix.cc) || '' }}${{ !startsWith(matrix.os, 'ubuntu') && format(' | {0}', matrix.os) || '' }})
    runs-on: ${{matrix.os}}

    env:
      SIM: ${{ matrix.simulator }}
      TOPLEVEL_LANG: ${{ matrix.toplevel_lang }}
      CXX_STANDARD: ${{ matrix.cxx-standard }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        simulator: [nvc]
        os: [ubuntu-24.04]
        nvc-version: ["1.20.1"]
        toplevel_lang: [vhdl]
        cxx-standard: ["20"]
        include:
          # Ubuntu with Clang
          - python-version: "3.13"
            nvc-version: "1.20.1"
            os: "ubuntu-24.04"
            simulator: "nvc"
            toplevel_lang: "vhdl"
            cc: "clang"
            cxx: "clang++"
            gcov: "llvm-cov gcov"
            cxx-standard: "20"
          # MacOS ARM and Intel
          - python-version: "3.13"
            simulator: "icarus"
            toplevel_lang: "verilog"
            os: "macos-26"
            cxx-standard: "20"
          - python-version: "3.13"
            simulator: "icarus"
            toplevel_lang: "verilog"
            os: "macos-15-intel"
            cxx-standard: "20"
          # Other C++ standards with GCC
          - python-version: "3.13"
            nvc-version: "1.20.1"
            os: "ubuntu-24.04"
            simulator: "nvc"
            toplevel_lang: "vhdl"
            cxx-standard: "23"

    steps:
    - uses: actions/checkout@v6.0.2
      with:
        # GitHub PR's create a merge commit, and Actions are run on that commit.
        # Codecov's uploader needs the previous commit (tip of PR branch) to associate coverage correctly.
        # A fetch depth of 2 provides enough information without fetching the entire history.
        fetch-depth: 2

    - uses: actions/setup-python@v6
      with:
        python-version: ${{matrix.python-version}}
        allow-prereleases: true

    - name: Setup NVC
      uses: nickg/setup-nvc@v1
      if: matrix.simulator == 'nvc'
      with:
        version: ${{matrix.nvc-version}}

    - name: Setup Icarus (MacOS)
      if: matrix.simulator == 'icarus' && startsWith(matrix.os, 'macos')
      run: |
        brew install icarus-verilog

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        activate-environment: "true"

    - name: Install Testing Dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt install -y make libgtest-dev llvm

    - name: Checkout cocotb
      uses: actions/checkout@v6.0.2
      with:
        repository: cocotb/cocotb
        path: cocotb

    - name: Run tests
      env:
        CC: ${{ matrix.cc || 'gcc' }}
        CXX: ${{ matrix.cxx || 'g++' }}
        GCOV_EXECUTABLE: ${{ matrix.gcov || 'gcov' }}
        CXX_STANDARD: ${{ matrix.cxx-standard }}
        DEV_BUILD_DEP_GROUP: dev_tests
      run: |
        make dev_tests integration_tests generate_report

    - name: Check stubs haven't diverged
      run: |
        git diff --exit-code -- python/_coconext.pyi

    - name: Upload coverage reports to Codecov
      if: github.repository == 'ktbarrett/coconext'
      uses: codecov/codecov-action@v6
      with:
        disable_search: true
        plugins: noop
        files: .python-coverage.xml,.cpp-coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
        fail_ci_if_error: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'dev') }}
