name: Auto-merge locked dependencies upgrade

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Enable auto-merge
    if: github.head_ref == 'upgrade-locked-dependencies'
    runs-on: ubuntu-latest
    steps:

    - name: Generate GitHub App Token
      id: app-token
      uses: actions/create-github-app-token@v3
      with:
        client-id: ${{ vars.PR_GITHUB_APP_ID }}
        private-key: ${{ secrets.PR_GITHUB_APP_PRIV_KEY }}

    - name: Enable Auto-Merge
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: gh pr merge --auto --squash "$PR_URL"
